### ISSUE TITLE
Getting Error of Empty Archive and No TSS in the zip file when extracted via 7zip

### ISSUE THREAD

**Issue by MarkTwynham** [walter-1/TSS#1]
Hi, I was asked to download the TSS tool set from a Microsoft Engineer but when I try to extract the zip file I get an error saying it is an empty folder and when I use 7zip I get an unexpected end of data. Could you help please?
![image](https://user-images.githubusercontent.com/11392488/125066010-6cd6a300-e0aa-11eb-84f4-0d28547a3f52.png)
![image](https://user-images.githubusercontent.com/11392488/125066060-7c55ec00-e0aa-11eb-9cec-46072743cdc1.png)

**Comment by MarkTwynham** [comment]
Sorry forgot to add - that when it extracted there is no tss (.cmd/.exe) file

**Comment by walter-1** [comment]
I cannot repro, zip downloads correct on my side.
Can you try on a different machine?
Mybe you company firewall blocks downloading zip files with executables inside

**Comment by MarkTwynham** [comment]
Hi Walter, yes it looks like the company is blocking or actually ripping data out of the download - I'll try another way - thanks a lot
