### ISSUE TITLE
TSS Tool Error Message

### ISSUE THREAD

**Issue by mackswift** [walter-1/TSS#2]
Hello Walter,

I was asked by Microsoft Support to run the TSS Tools as part of some SQL Server Troubleshooting. While attempting to run the command, I get the following error message.

.. invalid Script Path - Please avoid special characters in path, like spaces, exlamationMark, parenthesis

I'm attempting to run the tool on Server 2012 R2. I've saved the TSS Tools in different directory to resolve the error as it appears that the command doesn't like the directory. I tried c:\tools, c:\tss_tools, etc. to no avail. 

Any help would be greatly appreciated.

Thanks,
Bill

**Comment by walter-1** [comment]
more  information is required, like a screenshot of your attempt.
TSS never complaind so far if you start TSS from local disk b (i.e. C:\TSS_toos\tss ... ) on a folder without special chareactes like two consutive blanks/spaces or containing special characters like paranthesis ().

I hope that you downloaded latest version from Microsoft site:  https://cesdiagtools.blob.core.windows.net/windows/TSS.zip

**Comment by mackswift** [comment]
Thanks for the info, Walter. I'll try the TSS version you sent me as well. Below is the screenshot of my  attempt.

![image](https://user-images.githubusercontent.com/54779661/134568485-0ae17da5-c366-4f5f-a392-578725465863.png)

**Comment by walter-1** [comment]
closing issue because of lack of data (output data (C:\MS_DATA\ or logs from TSS_tools path to investigate further ). In known instances, the Path did contain a space. Moving files to a path with no space actually did resolve it those issues.
