### ISSUE TITLE
Run in remote session

### ISSUE THREAD

**Issue by iconiu** [walter-1/TSS#3]
This is more of a feature request than a bug.   Microsoft asked me to run this but found that results in a cold call to ask a user for 30 minutes of time to solve a problem I'm having.  There is a reason I'm not in sales...

Note that I was able to make some mods to mostly get it working on my own.  Here are some notes.
1.  I'm using DND_SetupReport
2.  Replace msinfo32 with get-computerinfo to prevent the popup during export.
3.  Remove the explorer folder popup when the zip was finalized.
4.  It seems to be getting stuck on SummaryReliability.vbs but everything prior gets collected.
5.  I had a really weird issue where it was ignoring the script parameters when using start-process powershell -argumentlist but worked ok with just & tssv1.ps1 -parameters.
6.  The silent mods + using an SCCM package to copy and run it was the best result.  I still had use enter-pssession to end the stuck vbs script even though SCCM has timed out the parent script after 30 minutes.   I was then able to zip up the 80MB of data already collected and copy it off using copy-item -from session.

**Comment by walter-1** [comment]
Thanks for the valuable input!
Please note, that TSS v1 is deprecated and will not be maintained further (This GitHub site is for TSS**v1** only)
TSS**v2** is the way to go, please see Public KB https://docs.microsoft.com/en-us/troubleshoot/windows-client/windows-troubleshooters/introduction-to-troubleshootingscript-toolset-tssv2 
I'n not sure, whether most of your items also apply for TSSv2  (but i.e. 3. "Remove the explorer folder popup" would apply.)

**Comment by walter-1** [comment]
Update: meanwhile TSSv2.ps1 progressed:
- when supplying switch -RemoteRun, it will suppress openign Explorer folder, don't start PSR/Video, dont start TSSclock window for scenarios..
- stuck on SummaryReliability.vbs" is being addressed as well

**Comment by walter-1** [comment]
**STATUS**: closing
most of issues running TSS either with PowerShell remoting or PsExec.exe have been addressed with necessary code changes of switch `-RemoteRun `     _- use when TSS is being executed on a remote host, i.e. via psExec or in PS Azure Serial Console; this will inhibit PSR, Video recording, starting TssClock and opening Explorer with final results. In such case also consider -AcceptEula_
